services:
  frontend:
    build: frontend
    image: talkyou-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: talkyou-frontend
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"

  backend:
    build: backend
    image: talkyou-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: talkyou-backend
    hostname: backend
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: "5G"
        reservations:
          cpus: "3"
          memory: "3G"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

networks:
  app:
    driver: bridge
